# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 05:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone', models.BigIntegerField(verbose_name='Телефoн')),
                ('email', models.EmailField(blank=True, max_length=250, verbose_name='E-mail')),
                ('comment', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'ordering': ['-pk'],
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзыв',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('seo_keyw', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ключевые слова')),
                ('seo_desc', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('slug', models.CharField(default='0', max_length=200, unique=True, verbose_name='название в url')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ['-pk'],
                'verbose_name_plural': 'Тексты',
                'verbose_name': 'Текст',
            },
        ),
        migrations.CreateModel(
            name='TextSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('name', models.SlugField(max_length=16, unique=True, verbose_name='Код')),
                ('val', models.TextField(max_length=1000, verbose_name='Значение')),
                ('file', models.FileField(blank=True, null=True, upload_to='settings', verbose_name='Файл')),
            ],
            options={
                'verbose_name_plural': 'текстовые переменные',
                'verbose_name': 'текстовая переменная',
            },
        ),
    ]
