# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.BooleanField(default=False, verbose_name='Публикация')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('comment', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзыв',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-pk'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
